# Generated by Django 2.1.2 on 2018-11-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('goal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('anonymous', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=1000)),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('goal', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=1000)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_fundraising.Campaign')),
            ],
        ),
        migrations.AddField(
            model_name='donations',
            name='fundraiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_fundraising.Fundraiser'),
        ),
    ]
