# Generated by Django 2.1.2 on 2018-11-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
    ]
