# Generated by Django 2.1.2 on 2018-12-27 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0004_auto_20181203_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 2, 44, 15, 997081)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='message',
            field=models.CharField(max_length=280),
        ),
    ]
