# Generated by Django 2.1.2 on 2018-12-27 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_fundraising', '0005_auto_20181227_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 2, 44, 39, 473618)),
        ),
    ]
