# Generated by Django 2.1.2 on 2018-12-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0007_auto_20181227_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='user',
        ),
    ]
