# Generated by Django 2.1.5 on 2019-01-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0009_fundraiser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='message',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='goal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='message',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
