# Generated by Django 2.1.5 on 2019-02-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0010_auto_20190131_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
