# Generated by Django 2.1.5 on 2019-02-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0011_fundraiser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
