# Generated by Django 2.2.2 on 2019-06-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0013_auto_20190430_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='country',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='donation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='province',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
