# Generated by Django 2.2.4 on 2019-08-18 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0015_remove_fundraiser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_message',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='default_fundraiser_message',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
