# Generated by Django 2.2.4 on 2019-12-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0017_auto_20191004_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
