# Generated by Django 2.2.4 on 2019-12-21 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0018_campaign_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
