# Generated by Django 2.2.10 on 2020-03-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0020_auto_20200308_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_message',
            field=models.TextField(),
        ),
    ]
