# Generated by Django 2.2.28 on 2023-06-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('team_fundraising', '0025_auto_20230620_2352'), ('team_fundraising', '0026_auto_20230621_0858')]

    dependencies = [
        ('team_fundraising', '0024_campaign_default_fundraiser_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='default_fundraiser_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='photo_small',
            field=models.ImageField(blank=True, upload_to='photos_small/'),
        ),
    ]
