# Generated by Django 2.2.28 on 2023-06-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0024_campaign_default_fundraiser_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='photo_800',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='default_fundraiser_amount',
            field=models.IntegerField(default=0),
        ),
    ]
