# Generated by Django 3.2.25 on 2024-04-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0025_auto_20230620_2352_squashed_0026_auto_20230621_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='team',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
