# Generated by Django 3.2.25 on 2024-04-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0026_fundraiser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
