# Generated by Django 5.2.15 on 2026-07-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_fundraising', '0027_campaign_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='photo_updated',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
