name: Auto-merge Dependabot minor updates

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Ensure PR is minor update
        id: check
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          shopt -s nocasematch
          if [[ "$PR_TITLE" =~ bump ]]; then
            echo "PR is a dependency bump"
          else
            echo "PR is not a dependency bump"
            exit 1
          fi
          if [[ "$PR_TITLE" =~ bump ]] && [[ ! "$PR_TITLE" =~ bump-major ]]; then
            echo "PR is a minor or patch update"
          else
            echo "PR is not a minor or patch update"
            exit 1
          fi
          shopt -u nocasematch

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        if: success()
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
